# Generated by Django 6.0.2 on 2026-02-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(db_index=True, max_length=100)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deals_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['agent_name'], name='leaderboard_agent_n_2dfb8f_idx')],
            },
        ),
    ]
